spring:
  application:
    name: movie15

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

jwt:
  #jwt.secret=8Fh3#T!s9@5mN&2QpV*Zy$w6LrXc1^kJb4Uz+Ao
  secret: ${JWT_SECRET_KEY}
  expiry-millis: 1800000  # 30분

cloud:
  aws:
    s3:
      bucket: codesix
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
